"""Assemble the multi-dimensional scorecard from existing result reports.

`docs/ROADMAP.md` §4 M5 asks for a scorecard covering repeatability,
cost, latency, precision, classification and the hard tier. Those numbers
already exist inside the raw reports in `eval/results/`; the failure mode
is a human copying them into a table and getting a denominator wrong.

So this module computes every figure **from the per-case runs**, the same
source `reviewer.verify` recomputes summaries from — never from a
report's own `summary` block, which is the thing being cross-checked, and
never from prose. Two denominators exist and are easy to conflate:

* **raw** — every observation the corpus asked for (cases x runs).
* **completed** — raw minus observations that ended in an error.

`summary.defect_cases` is the *completed* count, while the published
headline (e.g. "85/87") uses the *raw* denominator. Reporting one as the
other silently changes the claim, so both are emitted, always labelled.

Deliberately absent, per `docs/ROADMAP.md` §9 and
`eval/LEADERBOARD.md`: no composite score, no ranking, no
cross-corpus comparison. Rows are ordered by model identifier, and
reports are grouped by corpus fingerprint because results are only
comparable within one.
"""

import argparse
import glob
import json
import os
import sys

from .verify import _flat_runs, verify_report


def _pct(numerator, denominator):
    if not denominator:
        return "n/a"
    return f"{100.0 * numerator / denominator:.1f}%"


def summarize(report):
    """Derive every scorecard dimension from a report's raw runs."""
    runs = _flat_runs(report)
    defect = [r for r in runs if r.get("defect")]
    clean = [r for r in runs if not r.get("defect")]
    ok_defect = [r for r in defect if r.get("status") == "ok"]
    ok_clean = [r for r in clean if r.get("status") == "ok"]

    def scored(rows, key):
        return sum(1 for r in rows if (r.get("score") or {}).get(key))

    latencies = [
        r["metrics"]["latency_seconds"] for r in runs
        if isinstance(r.get("metrics"), dict)
        and r["metrics"].get("latency_seconds") is not None
    ]
    costs = [
        r["metrics"].get("external_cost_usd") for r in runs
        if isinstance(r.get("metrics"), dict)
        and r["metrics"].get("external_cost_usd") is not None
    ]

    # Repeatability is per *case*, not per observation: a defect found on
    # 2 of 3 runs is a different fact from one found on 3 of 3, and an
    # aggregate rate hides exactly that.
    always = sometimes = never = 0
    for case in report.get("cases", []):
        if not case.get("defect"):
            continue
        verdicts = [(r.get("score") or {}).get("detected")
                    for r in case.get("runs", []) if r.get("status") == "ok"]
        if not verdicts:
            continue
        if all(verdicts):
            always += 1
        elif any(verdicts):
            sometimes += 1
        else:
            never += 1

    return {
        "model": report.get("model", "?"),
        "backend": report.get("backend", "?"),
        "runs_per_case": report.get("runs_per_case"),
        "corpus_sha256": (report.get("corpus") or {}).get("sha256", ""),
        "case_count": (report.get("corpus") or {}).get("case_count"),
        "raw_defect": len(defect),
        "raw_clean": len(clean),
        "completed_defect": len(ok_defect),
        "completed_clean": len(ok_clean),
        "detected": scored(ok_defect, "detected"),
        "false_positives": scored(ok_clean, "false_positive"),
        "category_correct": scored(ok_defect, "category_correct"),
        "severity_correct": scored(ok_defect, "severity_correct"),
        "errors": sum(1 for r in runs if r.get("status") != "ok"),
        "defect_errors": len(defect) - len(ok_defect),
        "clean_errors": len(clean) - len(ok_clean),
        "always": always,
        "sometimes": sometimes,
        "never": never,
        "mean_latency": (sum(latencies) / len(latencies)) if latencies else None,
        "max_latency": max(latencies) if latencies else None,
        "external_cost_usd": sum(costs) if costs else None,
        "calls": len(runs),
    }


def _cost(row):
    if row["external_cost_usd"] is None:
        return "no external model API charge"
    return f"${row['external_cost_usd']:.6f}"


def render(rows):
    """Render grouped rows as markdown. Pure formatting, no arithmetic."""
    out = ["# Multi-dimensional scorecard",
           "",
           "**Generated by `bin/review-scorecard` from the raw reports in "
           "`eval/results/` — every figure is recomputed from per-case runs, "
           "not copied from a summary block or from prose. Regenerate rather "
           "than hand-edit.**",
           "",
           "Two denominators appear throughout and are never interchangeable:",
           "",
           "* **raw** — every observation the corpus asked for (cases x runs).",
           "* **completed** — raw minus observations that ended in a technical "
           "error.",
           "",
           "Errors are never folded into misses or into false positives.",
           "",
           "**This is not a ranking.** There is no composite score; rows are "
           "ordered by model identifier. Results are only comparable within a "
           "single corpus fingerprint, so each fingerprint is its own table. "
           "Cost and latency are not like-for-like across hosted and local "
           "execution — local runs are reported as *no external model API "
           "charge*, which is not the same as free.",
           ""]

    for sha, group in sorted(rows.items()):
        first = group[0]
        out += [f"## Corpus `{sha[:16]}…` — {first['case_count']} cases",
                "",
                f"Full fingerprint: `{sha}`",
                ""]
        out += ["| model | backend | runs | detection (raw) | detection (completed) | missed | clean FP (raw) | clean FP (completed) | category | severity | errors |",
                "|---|---|---|---|---|---|---|---|---|---|---|"]
        for r in sorted(group, key=lambda x: x["model"]):
            missed = r["completed_defect"] - r["detected"]
            out.append(
                f"| `{r['model']}` | {r['backend']} | {r['runs_per_case']} "
                f"| {r['detected']}/{r['raw_defect']} ({_pct(r['detected'], r['raw_defect'])}) "
                f"| {r['detected']}/{r['completed_defect']} ({_pct(r['detected'], r['completed_defect'])}) "
                f"| {missed}/{r['completed_defect']} "
                f"| {r['false_positives']}/{r['raw_clean']} ({_pct(r['false_positives'], r['raw_clean'])}) "
                f"| {r['false_positives']}/{r['completed_clean']} ({_pct(r['false_positives'], r['completed_clean'])}) "
                f"| {r['category_correct']}/{r['completed_defect']} "
                f"| {r['severity_correct']}/{r['completed_defect']} "
                f"| {r['errors']} ({r['defect_errors']} defect / {r['clean_errors']} clean) |")
        out += ["",
                "### Repeatability, latency and cost",
                "",
                "Repeatability counts **defective cases**, not observations: "
                "a defect found on 2 of 3 runs is a different fact from one "
                "found on 3 of 3, and a rate hides that.",
                "",
                "| model | always detected | sometimes | never | mean latency | max latency | external cost |",
                "|---|---|---|---|---|---|---|"]
        for r in sorted(group, key=lambda x: x["model"]):
            mean = f"{r['mean_latency']:.1f}s" if r["mean_latency"] is not None else "n/a"
            mx = f"{r['max_latency']:.1f}s" if r["max_latency"] is not None else "n/a"
            out.append(f"| `{r['model']}` | {r['always']} | {r['sometimes']} "
                       f"| {r['never']} | {mean} | {mx} | {_cost(r)} |")
        out.append("")
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="review-scorecard",
        description="Assemble the multi-dimensional scorecard from existing "
                    "result reports. Computes, never copies.")
    parser.add_argument("reports", nargs="*",
                        help="report JSON files (default: eval/results/*.json, "
                             "excluding checkpoints and provisional runs)")
    parser.add_argument("--out", help="write markdown here (default: stdout)")
    args = parser.parse_args(argv)

    paths = args.reports
    if not paths:
        root = os.environ.get("AI_DEV_HOME", ".")
        paths = sorted(
            p for p in glob.glob(os.path.join(root, "eval", "results", "*.json"))
            if "checkpoint" not in os.path.basename(p))
    if not paths:
        print("review-scorecard: no report files found", file=sys.stderr)
        return 2

    rows, failed = {}, []
    for path in paths:
        try:
            with open(path, encoding="utf-8") as handle:
                report = json.load(handle)
        except (OSError, ValueError) as exc:
            failed.append(f"{path}: unreadable ({exc})")
            continue
        # A report that is not internally consistent must not be quoted:
        # the whole point of this file is that its numbers can be trusted.
        errors, _ = verify_report(report, origin=path)
        if errors:
            failed.append(f"{path}: not internally consistent — {errors[0]}")
            continue
        row = summarize(report)
        rows.setdefault(row["corpus_sha256"], []).append(row)

    for message in failed:
        print(f"review-scorecard: skipped {message}", file=sys.stderr)
    if not rows:
        print("review-scorecard: no usable reports", file=sys.stderr)
        return 2

    text = render(rows)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(text + "\n")
        print(f"review-scorecard: wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
